### ISSUE TITLE
Переделать параметры конструктора плагинов на деструктор

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.editor#373]
## Editor's Core

- [x] Prepare Block Tools (#381)
- [x] Prepare Inline Tools (#379)

## Block Tools

- [x] Paragraph (codex-editor/paragraph#4)
- [x] Header (codex-editor/header#8)
- [x] List (codex-editor/list#3)
- [x] Quote (codex-editor/quote#3)
- [x] Simple Image (codex-editor/simple-image#2)
- [x] Delimiter (codex-editor/delimiter#2)

## Inline Tools

- [x] Inline Code (codex-editor/inline-code#2)
- [x] Bold (#379)
- [x] Italic (#379)
- [x] Link (#379)
